# Generated by Django 3.2.19 on 2023-06-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kev_estore', '0002_auto_20230623_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='clothing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='clubs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
