# Generated by Django 3.2.19 on 2023-06-30 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kev_estore', '0003_auto_20230627_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='accessories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kev_estore.accessories'),
        ),
        migrations.AddField(
            model_name='item',
            name='clubs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kev_estore.clubs'),
        ),
    ]
