# Generated by Django 3.2.19 on 2023-07-01 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kev_estore', '0006_auto_20230630_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='accessories_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='clothing_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='clubs_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kev_estore.accessories'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='clothing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kev_estore.clothing'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='clubs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kev_estore.clubs'),
        ),
    ]
