# Generated by Django 3.2.19 on 2023-07-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kev_estore', '0011_alter_subscribedusers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedusers',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscribedusers',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
