# Generated by Django 3.2.19 on 2023-07-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kev_estore', '0007_auto_20230701_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='clothing',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
