# Generated by Django 3.2.19 on 2023-07-04 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kev_estore', '0008_auto_20230701_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clothing',
            new_name='GolfGear',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='clothing',
            new_name='golfgear',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='accessories_quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='clothing_quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='clubs',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='clubs_quantity',
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='Clubs',
        ),
    ]
