# Generated by Django 3.2.19 on 2023-07-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kev_estore', '0010_subscribedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedusers',
            name='email',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
