# Generated by Django 3.2.19 on 2023-11-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kev_estore', '0013_auto_20231103_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='golfgear',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
