# Generated by Django 3.2.19 on 2023-11-17 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kev_estore', '0014_auto_20231106_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribedUsers',
        ),
    ]
